#! /bin/bash

aptitude install shorewall

tee /etc/shorewall/interfaces <<EOF
###############################################################################
#ZONE   INTERFACE       BROADCAST       OPTIONS
net     eth0
gfw     hole
EOF

tee /etc/shorewall/policy <<EOF
###############################################################################
#SOURCE DEST    POLICY          LOG     LIMIT:          CONNLIMIT:
#                               LEVEL   BURST           MASK
fw      all     ACCEPT
all     fw      ACCEPT
gfw     all     ACCEPT
all     all     REJECT
EOF

tee /etc/shorewall/snat <<EOF
###################################################################################################################
#ACTION         SOURCE          DEST            PROTO   PORT   IPSEC  MARK   USER    SWITCH  ORIGDEST   PROBABILITY
MASQUERADE      192.168.0.0/16  eth0
MASQUERADE      172.28.0.0/16   eth0
MASQUERADE      172.31.0.0/16   eth0
EOF

tee /etc/shorewall/zones <<EOF
###############################################################################
#ZONE   TYPE            OPTIONS         IN                      OUT
#                                       OPTIONS                 OPTIONS
fw      firewall
net     ipv4
gfw     ipv4
EOF

systemctl enable shorewall.service
systemctl restart shorewall.service

tee /etc/sysctl.d/51-ip_forward.conf <<EOF
net.ipv4.ip_forward=1
EOF

sysctl -p /etc/sysctl.d/51-ip_forward.conf
