#! /bin/sh

TUN_LOCAL_ADDRESS=$(ip -4 addr show hole | grep -oP '(?<=inet\s)\d+(\.\d+){3}')
TUN_PEER_ADDRESS=$(ip -4 addr show hole | grep -oP '(?<=peer\s)\d+(\.\d+){3}')

echo Using TUN address $TUN_LOCAL_ADDRESS peer $TUN_PEER_ADDRESS

echo Enable frr ospfd

sed -i 's/^ospfd=no$/ospfd=yes/g' /etc/frr/daemons

echo Restarting frr

systemctl restart frr.service

echo Configure ospfd

vtysh << EOF
configure terminal

ip router-id ${TUN_LOCAL_ADDRESS}

router ospf
 no ospf router-id
 network 172.31.0.0/16 area 0.0.0.0
 default-information originate metric 50
exit

ip prefix-list INSTALL seq 100 permit 172.16.0.0/12 ge 12
ip prefix-list INSTALL seq 101 permit 192.168.0.0/16 ge 16
ip prefix-list INSTALL seq 200 deny any

route-map INSTALL permit 100
 match ip address prefix-list INSTALL
exit

ip protocol any route-map INSTALL

end

write
EOF

systemctl restart frr.service

echo Done
