#! /bin/bash

systemctl --user stop gpg-agent-browser.socket
systemctl --user mask gpg-agent-browser.socket

systemctl --user stop gpg-agent-extra.socket
systemctl --user mask gpg-agent-extra.socket

systemctl --user stop gpg-agent-ssh.socket
systemctl --user mask gpg-agent-ssh.socket

systemctl --user stop gpg-agent.socket
systemctl --user mask gpg-agent.socket

gpgconf --kill gpg-agent
gpgconf --kill dirmngr
gpgconf --remove-socketdir
gpgconf --create-socketdir

systemctl --user start dirmngr.service

if [ $(gpgconf --list-dirs agent-socket) != /run/user/1000/gnupg/S.gpg-agent ] ; then
    echo "$(tput bold)Warning$(tput sgr0): Your gpg agent socket is wrong $(gpgconf --list-dirs agent-socket)"
    exit 1
fi

gpg --recv-keys 3640DD71F863C6DEA7DB8680CE1F766CAF00382D
gpg --import-ownertrust < "$(dirname ${BASH_SOURCE[0]})/ownertrust"
