#!/usr/bin/env zsh

# Set to this to use case-sensitive completion
CASE_SENSITIVE="true"

# Comment this out to disable bi-weekly auto-update checks
DISABLE_AUTO_UPDATE="true"

# Uncomment to change how often before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want to disable command autocorrection
DISABLE_CORRECTION="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
COMPLETION_WAITING_DOTS="true"


# ZINIT initialize
ZINIT_HOME="${HOME}/.local/share/zinit/zinit.git"
if [ ! -d "${ZINIT_HOME}" ]; then
  mkdir -p "$(dirname $ZINIT_HOME)"
  git clone https://github.com/zdharma-continuum/zinit.git "$ZINIT_HOME"
fi
source "${ZINIT_HOME}/zinit.zsh"

# Load OMZ libs
zinit snippet OMZL::compfix.zsh
zinit snippet OMZL::completion.zsh
zinit snippet OMZL::directories.zsh
zinit snippet OMZL::functions.zsh
zinit snippet OMZL::git.zsh
zinit snippet OMZL::grep.zsh
zinit snippet OMZL::history.zsh
zinit snippet OMZL::key-bindings.zsh
zinit snippet OMZL::misc.zsh
zinit snippet OMZL::spectrum.zsh
zinit snippet OMZL::termsupport.zsh
zinit snippet OMZL::theme-and-appearance.zsh

# Load OMZ plugins
zinit snippet OMZP::git
zinit snippet OMZP::systemd
zinit snippet OMZP::per-directory-history/per-directory-history.zsh

# Load OMZ theme
zinit snippet OMZT::kphoen

if [ ! -n "$SSH_AUTH_SOCK" ] ; then
	export SSH_AUTH_SOCK="/tmp/ssh-agent.$USER.socket"
	ssh-add -l >/dev/null 2>/dev/null
	if [ "$?" -eq 2 ] ; then
		rm -f "$SSH_AUTH_SOCK"
		ssh-agent -a "$SSH_AUTH_SOCK" > /dev/null
	fi
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi

change_title_bar () {
    title "$(hostname) $(basename $PWD) ($(git rev-parse --abbrev-ref HEAD 2>/dev/null)): $2"
}

add-zsh-hook precmd change_title_bar
add-zsh-hook preexec change_title_bar

# Customize to your needs...
bindkey "^U" backward-kill-line
bindkey "^W" vi-backward-kill-word
bindkey "^[[1;3C" vi-forward-word
bindkey "^[[1;3D" vi-backward-word

source ~/.zshrc.local 2>/dev/null

# load additional configuration
if [[ -d ~/.zshrc.d ]]; then
    for file in ~/.zshrc.d/*.zsh; do
        source "$file"
    done
    unset file
fi
