#!/usr/bin/env zsh

# Set to this to use case-sensitive completion
CASE_SENSITIVE="true"

# Comment this out to disable bi-weekly auto-update checks
DISABLE_AUTO_UPDATE="true"

# Uncomment to change how often before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want to disable command autocorrection
DISABLE_CORRECTION="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
COMPLETION_WAITING_DOTS="true"

HOST=$(hostname -f)

# ZINIT initialize
ZINIT_HOME="${HOME}/.local/share/zinit/zinit.git"
if [ ! -d "${ZINIT_HOME}" ]; then
  mkdir -p "$(dirname $ZINIT_HOME)"
  git clone https://github.com/zdharma-continuum/zinit.git "$ZINIT_HOME"
fi
source "${ZINIT_HOME}/zinit.zsh"

# Load OMZ libs
zinit snippet OMZL::compfix.zsh
zinit snippet OMZL::completion.zsh
zinit snippet OMZL::directories.zsh
zinit snippet OMZL::functions.zsh
zinit snippet OMZL::git.zsh
zinit snippet OMZL::grep.zsh
zinit snippet OMZL::history.zsh
zinit snippet OMZL::key-bindings.zsh
zinit snippet OMZL::misc.zsh
zinit snippet OMZL::spectrum.zsh
zinit snippet OMZL::termsupport.zsh
zinit snippet OMZL::theme-and-appearance.zsh

# Load OMZ plugins
zinit snippet OMZP::git
zinit snippet OMZP::systemd
zinit snippet OMZP::per-directory-history/per-directory-history.zsh

autoload -Uz compinit && compinit

### Begin prompt

# Need this so the prompt will work.
setopt prompt_subst

# See if we can use colors.
autoload zsh/terminfo
for color in RED GREEN YELLOW BLUE MAGENTA CYAN WHITE GREY; do
  typeset -g PR_$color="%{$terminfo[bold]$fg[${(L)color}]%}"
  typeset -g PR_LIGHT_$color="%{$fg[${(L)color}]%}"
done
PR_NO_COLOUR="%{$terminfo[sgr0]%}"

# Modify Git prompt
ZSH_THEME_GIT_PROMPT_PREFIX="%{$fg[red]%}"
ZSH_THEME_GIT_PROMPT_SUFFIX="%{$reset_color%}"
ZSH_THEME_GIT_PROMPT_DIRTY=""
ZSH_THEME_GIT_PROMPT_CLEAN=""

ZSH_THEME_GIT_PROMPT_ADDED="%{$fg[green]%} %{%G✚%}"
ZSH_THEME_GIT_PROMPT_MODIFIED="%{$fg[blue]%} %{%G✹%}"
ZSH_THEME_GIT_PROMPT_DELETED="%{$fg[red]%} %{%G✖%}"
ZSH_THEME_GIT_PROMPT_RENAMED="%{$fg[magenta]%} %{%G➜%}"
ZSH_THEME_GIT_PROMPT_UNMERGED="%{$fg[yellow]%} %{%G═%}"
ZSH_THEME_GIT_PROMPT_UNTRACKED="%{$fg[cyan]%} %{%G✭%}"

PR_HBAR="─"

# Finally, the prompt.
PR_BARS='%{${PR_CYAN}${(pl:${COLUMNS}::$PR_HBAR:)}$terminfo[cr]%}'
PR_1='${PR_GREY}[${PR_CYAN}%(!.%SROOT%s.%n)${PR_GREY}@${PR_YELLOW}%M${PR_GREY}:${PR_GREEN}%~${PR_GREY}]%{%G$terminfo[cuf1]%}'
PR_2='${PR_BLUE}($(git_prompt_info)$(git_prompt_status)${PR_BLUE})%{%G$terminfo[cuf1]%}'
PR_3='%(?..${PR_BLUE}(${PR_RED}%?↵${PR_BLUE}%)%{%G$terminfo[cuf1]%})'
PR_4='${PR_BLUE}(${PR_YELLOW}$$${PR_GREY}/${PR_YELLOW}%j${PR_BLUE}%)%{%G$terminfo[cuf1]%}'
PR_5='${PR_BLUE}(${PR_YELLOW}%D{%Y %b %d} ${PR_MAGENTA}%D{%H:%M:%S}${PR_BLUE})%{%G$terminfo[cuf1]%}'

PROMPT="${PR_BARS}${PR_1}${PR_2}${PR_3}${PR_4}${PR_5}
%#${PR_NO_COLOUR} "

PS2='${PR_BLUE}(${PR_LIGHT_GREEN}%_${PR_BLUE})>${PR_NO_COLOUR} '

### End prompt

change_title_bar () {
    title "$(hostname) $(basename $PWD) ($(git rev-parse --abbrev-ref HEAD 2>/dev/null)): $2"
}

add-zsh-hook precmd change_title_bar
add-zsh-hook preexec change_title_bar

if [ ! -n "$SSH_AUTH_SOCK" ] ; then
	export SSH_AUTH_SOCK="/tmp/ssh-agent.$USER.socket"
	ssh-add -l >/dev/null 2>/dev/null
	if [ "$?" -eq 2 ] ; then
		rm -f "$SSH_AUTH_SOCK"
		ssh-agent -a "$SSH_AUTH_SOCK" > /dev/null
	fi
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi

# Customize to your needs...
bindkey "^U" backward-kill-line
bindkey "^W" vi-backward-kill-word
bindkey "^[[1;3C" vi-forward-word
bindkey "^[[1;3D" vi-backward-word

source ~/.zshrc.local 2>/dev/null

# load additional configuration
if [[ -d ~/.zshrc.d ]]; then
    for file in ~/.zshrc.d/*.zsh; do
        source "$file"
    done
    unset file
fi
