#!/usr/bin/env zsh

# Set to this to use case-sensitive completion
CASE_SENSITIVE="true"

# Comment this out to disable bi-weekly auto-update checks
DISABLE_AUTO_UPDATE="true"

# Uncomment to change how often before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want to disable command autocorrection
DISABLE_CORRECTION="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
COMPLETION_WAITING_DOTS="true"

source ~/.zpm/zpm.zsh 2>/dev/null || {
  git clone https://github.com/zpm-zsh/zpm ~/.zpm
  source ~/.zpm/zpm.zsh
}

### OpenWrt
#zpm if openwrt load zpm-zsh/openwrt


### Termux
#zpm if termux load zpm-zsh/termux

### Tmux
#zpm if ssh load zpm-zsh/tmux
#zpm if-not ssh load zpm-zsh/tmux,apply:path

### VTE
#zpm if vte load zpm-zsh/vte

### 3party plugins
#zpm load                              \
#  zpm-zsh/core-config                 \
#  zpm-zsh/ignored-users,async         \
#  zpm-zsh/check-deps,async            \
#  zpm-zsh/minimal-theme               \
#  zpm-zsh/ls,async                    \
#  zpm-zsh/colorize,async              \
#  zpm-zsh/ssh,async                   \
#  zpm-zsh/dot,async                   \
#  zpm-zsh/undollar,async

### Plugins for local host
#zpm if-not ssh load                                                                    \
#  zpm-zsh/dropbox,async                                                                \
#  zpm-zsh/zsh-better-npm-completion,async                                              \
#                                                                                       \
#  zpm-zsh/clipboard                                                                    \
#  zpm-zsh/mysql-colorize,async                                                         \
#  zpm-zsh/bookmarks,async                                                              \
#  zpm-zsh/autoenv,async                                                                \
#                                                                                       \
#  mdumitru/fancy-ctrl-z,async                                                          \
#  zsh-users/zsh-history-substring-search,source:zsh-history-substring-search.zsh,async \
#  zsh-users/zsh-autosuggestions,source:zsh-autosuggestions.zsh,async

# Pull in OMZ (doesn't actually source anything)
zpm load @omz

# Load any OMZ libraries we want or our OMZ plugins require
zpm load                \
  @omz-lib/compfix      \
  @omz-lib/completion   \
  @omz-lib/directories  \
  @omz-lib/functions    \
  @omz-lib/git          \
  @omz-lib/grep         \
  @omz-lib/history      \
  @omz-lib/key-bindings \
  @omz-lib/misc         \
  @omz-lib/spectrum     \
  @omz-lib/termsupport  \
  @omz-lib/theme-and-appearance

# Load some OMZ plugins and theme
zpm load          \
  @omz/git        \
  @omz/systemd    \
  @omz/per-directory-history

zpm load @omz-theme/kphoen

if [ ! -n "$SSH_AUTH_SOCK" ] ; then
	export SSH_AUTH_SOCK="/tmp/ssh-agent.$USER.socket"
	ssh-add -l >/dev/null 2>/dev/null
	if [ "$?" -eq 2 ] ; then
		rm -f "$SSH_AUTH_SOCK"
		ssh-agent -a "$SSH_AUTH_SOCK" > /dev/null
	fi
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi

change_title_bar () {
    title "$(basename $PWD) ($(git rev-parse --abbrev-ref HEAD 2>/dev/null)): $2"
}

add-zsh-hook precmd change_title_bar
add-zsh-hook preexec change_title_bar

# Customize to your needs...
bindkey "^U" backward-kill-line
bindkey "^W" vi-backward-kill-word
bindkey "^[[1;3C" vi-forward-word
bindkey "^[[1;3D" vi-backward-word

source ~/.zshrc.local 2>/dev/null

# load additional configuration
if [[ -d ~/.zshrc.d ]]; then
    for file in ~/.zshrc.d/*.zsh; do
        source "$file"
    done
    unset file
fi
